substitutions:
  _SERVICE_NAME: citizen-demand-ai
  _REGION: asia-south1

steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/citizen-demand/app:${SHORT_SHA}", "."]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/citizen-demand/app:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/citizen-demand/app:${SHORT_SHA}

